[package]
name = "bvm"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.0", features = ["derive"] }
byteorder = "1.4.3"
bitflags = "1.3.2"
zip = "0.5.13"